<?php
/**
 * ECommerceProductApiModel
 *
 * PHP version 5
 *
 * @category Class
 * @package  RevampCRM\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * RevampCRM Developer API
 *
 * You can use this API to access Account related info and contacts. We currently support Basic Authentication. Using 'Username' and either 'Password' Or 'API Key' as the password
 *
 * OpenAPI spec version: v1
 * Contact: crm@revampco.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace RevampCRM\Models;

use \ArrayAccess;

/**
 * ECommerceProductApiModel Class Doc Comment
 *
 * @category    Class */
/** 
 * @package     RevampCRM\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ECommerceProductApiModel implements ArrayAccess
{
    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'ECommerceProductApiModel';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = array(
        '_id' => 'string',
        'account_id' => 'string',
        'contact_id' => 'string',
        'user_id' => 'string',
        'created_on' => '\DateTime',
        'updated_on' => '\DateTime',
        'vendor' => 'string',
        'e_commerce_provider_name' => 'string',
        'provider_store_id' => 'string',
        'provider_product_id' => 'string',
        'provider_product_name' => 'string',
        'product_type' => 'string',
        'tags' => 'string',
        'variants' => '\RevampCRM\Models\ECommerceProductVariant[]',
        'categories' => '\RevampCRM\Models\ECommerceCategoryApiModel[]',
        'image' => 'string',
        'product_handle' => 'string'
    );

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = array(
        '_id' => '_id',
        'account_id' => 'AccountId',
        'contact_id' => 'ContactId',
        'user_id' => 'UserId',
        'created_on' => 'CreatedOn',
        'updated_on' => 'UpdatedOn',
        'vendor' => 'Vendor',
        'e_commerce_provider_name' => 'ECommerceProviderName',
        'provider_store_id' => 'ProviderStoreId',
        'provider_product_id' => 'ProviderProductId',
        'provider_product_name' => 'ProviderProductName',
        'product_type' => 'ProductType',
        'tags' => 'tags',
        'variants' => 'variants',
        'categories' => 'categories',
        'image' => 'Image',
        'product_handle' => 'ProductHandle'
    );

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = array(
        '_id' => 'setId',
        'account_id' => 'setAccountId',
        'contact_id' => 'setContactId',
        'user_id' => 'setUserId',
        'created_on' => 'setCreatedOn',
        'updated_on' => 'setUpdatedOn',
        'vendor' => 'setVendor',
        'e_commerce_provider_name' => 'setECommerceProviderName',
        'provider_store_id' => 'setProviderStoreId',
        'provider_product_id' => 'setProviderProductId',
        'provider_product_name' => 'setProviderProductName',
        'product_type' => 'setProductType',
        'tags' => 'setTags',
        'variants' => 'setVariants',
        'categories' => 'setCategories',
        'image' => 'setImage',
        'product_handle' => 'setProductHandle'
    );

    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = array(
        '_id' => 'getId',
        'account_id' => 'getAccountId',
        'contact_id' => 'getContactId',
        'user_id' => 'getUserId',
        'created_on' => 'getCreatedOn',
        'updated_on' => 'getUpdatedOn',
        'vendor' => 'getVendor',
        'e_commerce_provider_name' => 'getECommerceProviderName',
        'provider_store_id' => 'getProviderStoreId',
        'provider_product_id' => 'getProviderProductId',
        'provider_product_name' => 'getProviderProductName',
        'product_type' => 'getProductType',
        'tags' => 'getTags',
        'variants' => 'getVariants',
        'categories' => 'getCategories',
        'image' => 'getImage',
        'product_handle' => 'getProductHandle'
    );

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = array();

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['_id'] = isset($data['_id']) ? $data['_id'] : null;
        $this->container['account_id'] = isset($data['account_id']) ? $data['account_id'] : null;
        $this->container['contact_id'] = isset($data['contact_id']) ? $data['contact_id'] : null;
        $this->container['user_id'] = isset($data['user_id']) ? $data['user_id'] : null;
        $this->container['created_on'] = isset($data['created_on']) ? $data['created_on'] : null;
        $this->container['updated_on'] = isset($data['updated_on']) ? $data['updated_on'] : null;
        $this->container['vendor'] = isset($data['vendor']) ? $data['vendor'] : null;
        $this->container['e_commerce_provider_name'] = isset($data['e_commerce_provider_name']) ? $data['e_commerce_provider_name'] : null;
        $this->container['provider_store_id'] = isset($data['provider_store_id']) ? $data['provider_store_id'] : null;
        $this->container['provider_product_id'] = isset($data['provider_product_id']) ? $data['provider_product_id'] : null;
        $this->container['provider_product_name'] = isset($data['provider_product_name']) ? $data['provider_product_name'] : null;
        $this->container['product_type'] = isset($data['product_type']) ? $data['product_type'] : null;
        $this->container['tags'] = isset($data['tags']) ? $data['tags'] : null;
        $this->container['variants'] = isset($data['variants']) ? $data['variants'] : null;
        $this->container['categories'] = isset($data['categories']) ? $data['categories'] : null;
        $this->container['image'] = isset($data['image']) ? $data['image'] : null;
        $this->container['product_handle'] = isset($data['product_handle']) ? $data['product_handle'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = array();
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properteis are valid
     */
    public function valid()
    {
        return true;
    }


    /**
     * Gets _id
     * @return string
     */
    public function getId()
    {
        return $this->container['_id'];
    }

    /**
     * Sets _id
     * @param string $_id
     * @return $this
     */
    public function setId($_id)
    {
        $this->container['_id'] = $_id;

        return $this;
    }

    /**
     * Gets account_id
     * @return string
     */
    public function getAccountId()
    {
        return $this->container['account_id'];
    }

    /**
     * Sets account_id
     * @param string $account_id
     * @return $this
     */
    public function setAccountId($account_id)
    {
        $this->container['account_id'] = $account_id;

        return $this;
    }

    /**
     * Gets contact_id
     * @return string
     */
    public function getContactId()
    {
        return $this->container['contact_id'];
    }

    /**
     * Sets contact_id
     * @param string $contact_id
     * @return $this
     */
    public function setContactId($contact_id)
    {
        $this->container['contact_id'] = $contact_id;

        return $this;
    }

    /**
     * Gets user_id
     * @return string
     */
    public function getUserId()
    {
        return $this->container['user_id'];
    }

    /**
     * Sets user_id
     * @param string $user_id
     * @return $this
     */
    public function setUserId($user_id)
    {
        $this->container['user_id'] = $user_id;

        return $this;
    }

    /**
     * Gets created_on
     * @return \DateTime
     */
    public function getCreatedOn()
    {
        return $this->container['created_on'];
    }

    /**
     * Sets created_on
     * @param \DateTime $created_on
     * @return $this
     */
    public function setCreatedOn($created_on)
    {
        $this->container['created_on'] = $created_on;

        return $this;
    }

    /**
     * Gets updated_on
     * @return \DateTime
     */
    public function getUpdatedOn()
    {
        return $this->container['updated_on'];
    }

    /**
     * Sets updated_on
     * @param \DateTime $updated_on
     * @return $this
     */
    public function setUpdatedOn($updated_on)
    {
        $this->container['updated_on'] = $updated_on;

        return $this;
    }

    /**
     * Gets vendor
     * @return string
     */
    public function getVendor()
    {
        return $this->container['vendor'];
    }

    /**
     * Sets vendor
     * @param string $vendor
     * @return $this
     */
    public function setVendor($vendor)
    {
        $this->container['vendor'] = $vendor;

        return $this;
    }

    /**
     * Gets e_commerce_provider_name
     * @return string
     */
    public function getECommerceProviderName()
    {
        return $this->container['e_commerce_provider_name'];
    }

    /**
     * Sets e_commerce_provider_name
     * @param string $e_commerce_provider_name
     * @return $this
     */
    public function setECommerceProviderName($e_commerce_provider_name)
    {
        $this->container['e_commerce_provider_name'] = $e_commerce_provider_name;

        return $this;
    }

    /**
     * Gets provider_store_id
     * @return string
     */
    public function getProviderStoreId()
    {
        return $this->container['provider_store_id'];
    }

    /**
     * Sets provider_store_id
     * @param string $provider_store_id
     * @return $this
     */
    public function setProviderStoreId($provider_store_id)
    {
        $this->container['provider_store_id'] = $provider_store_id;

        return $this;
    }

    /**
     * Gets provider_product_id
     * @return string
     */
    public function getProviderProductId()
    {
        return $this->container['provider_product_id'];
    }

    /**
     * Sets provider_product_id
     * @param string $provider_product_id
     * @return $this
     */
    public function setProviderProductId($provider_product_id)
    {
        $this->container['provider_product_id'] = $provider_product_id;

        return $this;
    }

    /**
     * Gets provider_product_name
     * @return string
     */
    public function getProviderProductName()
    {
        return $this->container['provider_product_name'];
    }

    /**
     * Sets provider_product_name
     * @param string $provider_product_name
     * @return $this
     */
    public function setProviderProductName($provider_product_name)
    {
        $this->container['provider_product_name'] = $provider_product_name;

        return $this;
    }

    /**
     * Gets product_type
     * @return string
     */
    public function getProductType()
    {
        return $this->container['product_type'];
    }

    /**
     * Sets product_type
     * @param string $product_type
     * @return $this
     */
    public function setProductType($product_type)
    {
        $this->container['product_type'] = $product_type;

        return $this;
    }

    /**
     * Gets tags
     * @return string
     */
    public function getTags()
    {
        return $this->container['tags'];
    }

    /**
     * Sets tags
     * @param string $tags
     * @return $this
     */
    public function setTags($tags)
    {
        $this->container['tags'] = $tags;

        return $this;
    }

    /**
     * Gets variants
     * @return \RevampCRM\Models\ECommerceProductVariant[]
     */
    public function getVariants()
    {
        return $this->container['variants'];
    }

    /**
     * Sets variants
     * @param \RevampCRM\Models\ECommerceProductVariant[] $variants
     * @return $this
     */
    public function setVariants($variants)
    {
        $this->container['variants'] = $variants;

        return $this;
    }

    /**
     * Gets categories
     * @return \RevampCRM\Models\ECommerceCategoryApiModel[]
     */
    public function getCategories()
    {
        return $this->container['categories'];
    }

    /**
     * Sets categories
     * @param \RevampCRM\Models\ECommerceCategoryApiModel[] $categories
     * @return $this
     */
    public function setCategories($categories)
    {
        $this->container['categories'] = $categories;

        return $this;
    }

    /**
     * Gets image
     * @return string
     */
    public function getImage()
    {
        return $this->container['image'];
    }

    /**
     * Sets image
     * @param string $image
     * @return $this
     */
    public function setImage($image)
    {
        $this->container['image'] = $image;

        return $this;
    }

    /**
     * Gets product_handle
     * @return string
     */
    public function getProductHandle()
    {
        return $this->container['product_handle'];
    }

    /**
     * Sets product_handle
     * @param string $product_handle
     * @return $this
     */
    public function setProductHandle($product_handle)
    {
        $this->container['product_handle'] = $product_handle;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\RevampCRM\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\RevampCRM\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


